#!/bin/sh

CURDIR=`dirname "$0"`
cd "$CURDIR"
SHA="ab651a2aa866351bdd089a4bf1d57f6a9bec2a66"
TARGET_PACKAGE="gccxml-${SHA}.zip"
TARGET_DIR="../inc/" # relative to $CURDIR
wget -O $TARGET_DIR/$TARGET_PACKAGE -c "https://github.com/gccxml/gccxml/archive/${SHA}.zip"
